Transactions/urls.py
from django.urls import path
from .views import DepositView, WithdrawView, LoanRequestView, ApproveLoanView, TransactionReportView, TransferBalanceView
urlpatterns = [
		path('deposit/', DepositView, name='deposit'),
		path('withdraw/', WithdrawView, name='withdraw'),
		path('loan_request/', LoanRequestView, name='loan_request'),
		path('approve_loan/<int:loan_id>/', ApproveLoanView, name='approve_loan'),
		path('transaction_report', TransactionReportView, name='transaction_report'),
		path('transfer', TransferBalanceView, name='transfer')
]

bank/urls.py
from django.contrib import admin
from django.urls import path, include
from .view import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name='home'), 
    path('acc/', include('Accounts.urls')),
    path('tns/', include('Transactions.urls'))
]

Transactions/models.py
from django.db import models
from django import forms
from Accounts.models import Account
from .constants import TRANSACTIONS_TYPE

# Create your models here.
class Transaction(models.Model):
	account = models.ForeignKey(Account, related_name='transactions', on_delete=models.CASCADE)

	amount= amount = models.DecimalField(max_digits=12, decimal_places=2)
	transaction_type= models.CharField(choices=TRANSACTIONS_TYPE, null=True, max_length=12)
	balance_after_transaction = models.DecimalField(max_digits=12, decimal_places=2)
	timestamp= models.DateTimeField(auto_now_add=True)
	loan_approv= models.BooleanField(default=False)

	

Transactions/forms.py
from django import forms
from decimal import Decimal
from .models import Transaction
from Accounts.models import Account
from .constants import TRANSACTIONS_TYPE

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount']

    def __init__(self, *args, **kwargs):
        self.user_account = kwargs.pop('account', None)
        super().__init__(*args, **kwargs)

class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit_amount:
            raise forms.ValidationError(f'You need to deposit at least ${min_deposit_amount}')
        return amount

class WithdrawForm(TransactionForm):
    def clean_amount(self):
        min_withdraw_amount = 10
        max_withdraw_amount = 50000
        balance = self.user_account.balance if self.user_account else None
        amount = self.cleaned_data.get('amount')

        if amount < min_withdraw_amount:
            raise forms.ValidationError(f'The minimum withdrawal amount is ${min_withdraw_amount}.')

        if balance < amount:
            raise forms.ValidationError('Insufficient Balance. Your account balance is too low.')
        
        if amount > max_withdraw_amount:
            raise forms.ValidationError(f'The maximum withdrawal amount is ${max_withdraw_amount}.')
        

        return amount



class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        balance=self.user_account.balance if self.user_account else None
        max_eligible_loan= balance*2
        amount = self.cleaned_data.get('amount')
        if max_eligible_loan < amount:
            raise forms.ValidationError(f'You are eligible loan in between {max_eligible_loan}')
        
        return amount
    

# class TransferBalanceFrom(forms.Form):
#     recipient_account_number= forms.IntegerField(label="Recipient's Account Number", required=True)
#     amount= forms.DecimalField(max_digits=12, decimal_places=2, required=True)

#     def __init__(self, *args, **kwargs):
#         sender_account_number= kwargs.pop('sender_account', None)
#         super().__init__(*args, **kwargs)

#     def clean(self):
#         cleaned_data = super().clean()
#         recipient_account_number = cleaned_data.get('recipient_account_number')
#         amount=cleaned_data.get('amount')
            
#         try:
#             recipient_account=Transaction.objects.filter(account_number=recipient_account_number)
#         except Account.DoesNotExist:
#             raise forms.ValidationError('The recipient account does not exit.')

#         if self.sender_account_number.balance < amount:
#             raise forms.ValidationError("Insufficient balance for this transaction.")
        
#         return cleaned_data



class TransferBalanceFrom(forms.Form):
    recipient_account_number= forms.IntegerField(
        label="Recipient's Account Number", 
        required=True,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter recipient account number'
        })
        )
    amount= forms.DecimalField(
        max_digits=12, 
        decimal_places=2, 
        required=True, 
        label="Recipient's Account Number", 
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter amount to ransfer'
        })
    )

Transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime  
from decimal import Decimal
from django.db.models import Sum

from django.conf import settings
from django.core.mail import send_mail
from Transactions.models import Transaction

from .forms import TransactionForm, DepositForm, WithdrawForm, LoanRequestForm, TransferBalanceFrom
from .constants import TRANSACTIONS_TYPE
from Accounts.models import Account

def TransactionView(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST, account=request.user.account)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('home'))
    else:
        form = TransactionForm(account=request.user.account)
    
    return render(request, 'transaction_form.html', {'form': form})

@login_required
def DepositView(request):
    account=request.user.account
    form=DepositForm(request.POST or None, account=account)
    if form.is_valid():
        transaction=form.save(commit=False)
        transaction.account=account
        transaction.transaction_type='deposit'
        transaction.balance_after_transaction= account.balance+transaction.amount
        account.balance=transaction.balance_after_transaction
        account.save()
        transaction.save()
        return redirect(reverse_lazy('home'))
    return render(request, 'transaction_form.html', {'form': form,  'title':'Deposit Money'})


@login_required
def WithdrawView(request):
    account = request.user.account 
    form = WithdrawForm(request.POST or None, account=account)
    
    if request.method == 'POST':
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.account = account
            transaction.transaction_type = 'withdraw'
            transaction.balance_after_transaction = account.balance - transaction.amount
            account.balance = transaction.balance_after_transaction
            account.save()
            transaction.save()
            return redirect('withdraw')
    
    return render(request, 'transaction_form.html', {'form': form, 'title':'Withdraw Money'})

@login_required
def LoanRequestView(request):
    account=request.user.account
    form=LoanRequestForm(request.POST or None, account=account)
    if request.method=="POST":
        if form.is_valid():
            current_loan_count=Transaction.objects.filter(
                account=account, transaction_type='loan', loan_approv=True).count()
            if current_loan_count>3:
                return HttpResponse('You crossed the loan limit')
            
            transaction=form.save(commit=False)
            transaction.account=account
            transaction.transaction_type='loan'
            transaction.balance_after_transaction=account.balance
            # transaction.loan_approv=True
            transaction.save()

            amount=form.cleaned_data.get('amount')
            messages.success(
                request,
                f'Loan request for {"{:,.2f}".format(float(amount))}$ submited succesfull'
            )
            return redirect('loan_request')
    loan_list=Transaction.objects.filter(account=account, transaction_type='loan')
    return render(request, 'transaction_form.html', {'form': form, 'loan_list':loan_list, 'title':'Loan Request'})

@login_required
def ApproveLoanView(request, loan_id):
    account=request.user.account
    # loan=Transaction.objects.filter(account=account, id=loan_id, transaction_type='loan')
    loan = get_object_or_404(Transaction, id=loan_id, transaction_type='loan')

    if not loan.loan_approv:
        loan.loan_approv = True
        loan.save()
        messages.success(request, 'Loan request approved successfully!')
    else:
        messages.info(request, 'This loan has already been approved.')
    return redirect('loan_request')


def TransactionReportView(request):
    account=request.user.account
    transactions= Transaction.objects.filter(account=account)

    balance=0
    start_date_str=request.GET.get('start_date')
    end_date_str=request.GET.get('end_date')

    if start_date_str and end_date_str:
        start_date_str=datetime.strptime(start_date_str, '%Y-%m-%d').date()
        end_date_str=datetime.strptime(end_date_str, '%Y-%m-%d').date()
    
        transactions = transactions.filter(
            timestamp__date__gte=start_date_str,
            timestamp__date__lte=end_date_str
        )
        
        balance = transactions.aggregate(Sum('amount'))['amount__sum'] or 0
    else:
        balance=account.balance

    context={
        'transactions': transactions.distinct(),
        'account': account,
        'balance': balance
    }

    return render(request, 'transaction_report.html', context)



# def TransferBalanceView(request):
#     sender_account=request.user.account
#     if request.method=='POST':
#         form=TransferBalanceFrom(request.POST, sender_account=sender_account)
#         if form.is_valid():
#             recipient_account_number=form.cleaned_data['recipient_account_number']
#             amount=form.cleaned_data['recipient_account_number']

#             recipient_account=Account.objects.filter(account_number=recipient_account_number)

#             sender_account.balance -=amount
#             sender_account.save()

#             recipient_account.balance +=amount
#             recipient_account.save()

#             Transaction.objects.create(
#                 account=sender_account.id,
#                 amount= amount,
#                 transaction_type='transfer',
#                 balance_after_transaction =sender_account.balance
#             )

#             Transaction.objects.create(
#                 account=recipient_account.id,
#                 amount= amount,
#                 transaction_type='deposit',
#                 balance_after_transaction =recipient_account.balance
#             )

#             messages.success(request, 'Amount Transfer Succesfull')
#             return redirect('transfer')
#     else:
#         form=TransferBalanceFrom()
    
#     context={
#         'form':form,
#         'title': 'Transfer Money'
#     }

#     return render(request, 'transfer.html', context)



def TransferBalanceView(request):
    if request.method == 'POST':
        form=TransferBalanceFrom(request.POST)
        if form.is_valid():
            recipient_account_number = form.cleaned_data['recipient_account_number']
            amount = form.cleaned_data['amount']
            
        
        try:
            recipient_account = get_object_or_404(Account, account_number=recipient_account_number)
        except Http404:
            messages.error(request, "Recipient account not found.")
            return redirect('transfer')

        sender_account = request.user.account
        
        # Ensure sufficient balance
        if sender_account.balance < amount:
            messages.error(request, "Insufficient balance for this transfer.")
            return redirect('transfer')

        # Proceed with the transfer
        sender_account.balance -= amount
        recipient_account.balance += amount




        sender_account.save()

        subject = 'Transfer Founds - Transaction',
        nl='\n'
        message = f"Dear { sender_account.user} , {nl} Funds ${amount}USD successully sended to {sender_account.account_number}. {nl} Your current is {sender_account.balance}, {nl} Thanks for banking with  us❤️"
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [sender_account.user.email ]
        send_mail( subject, message, email_from, recipient_list )

        recipient_account.save()
        # print("sender_account-", sender_account , " |account_number", sender_account.account_number , "| email-", sender_account.email)
        # send mail - Recever
        subject = 'Transfer Founds - Transaction',
        nl='\n'
        message = f"Dear { recipient_account.user} , {nl} Funds ${amount}USD Recived from Account Number {recipient_account.account_number}. {nl} Your current is ${recipient_account.balance}, {nl} Thanks for banking with us❤️"
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [recipient_account.user.email ]
        send_mail( subject, message, email_from, recipient_list )

        # Record the transaction for the sender
        Transaction.objects.create(
            account=sender_account,
            amount=amount,
            transaction_type='transfer_out',  # or 'debit' or any other suitable label
            balance_after_transaction=sender_account.balance,
        )

        # Record the transaction for the recipient
        Transaction.objects.create(
            account=recipient_account,
            amount=amount,
            transaction_type='transfer_in',  # or 'credit' or any other suitable label
            balance_after_transaction=recipient_account.balance,
        )

        messages.success(request, f"Successfully transferred {amount} to account {recipient_account_number}.")
        return redirect('transfer')  # Redirect to a success page or any other appropriate page
    else:
        form=TransferBalanceFrom()
    return render(request, 'transfer.html', {'form':form})

Transactions/templates/loan_list.html
{% block content %}




{% if title == "Loan Request" %}
    <div class="container mt-4">
        <h2>Loan Details</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#Id</th>
                    <th scope="col">Request Amount</th>
                    <th scope="col">Transaction Type</th>
                    <th scope="col">Balance</th>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Loan Approved</th>
                </tr>
            </thead>
            <tbody>
                {% for loan in loan_list %}
                    <tr>
                        <th scope="row">{{ loan.id }}</th>
                        <td>{{ loan.amount }}</td>
                        <td>{{ loan.get_transaction_type_display }}</td>
                        <td>{{ loan.balance_after_transaction }}</td>
                        <td>{{ loan.timestamp }}</td>
                        <td>
                            {% if loan.loan_approv %}
                                <span class="badge badge-success text-success">Approved</span>
                            {% else %}
															<a href="{% url 'approve_loan' loan.id %}" class="btn btn-primary">Approve</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}


{% endblock content %}

Transactions/templates/transaction_form.html
{% extends "base.html" %}

{% block title %}
<h1 class='text-center py-4'>{{title}}</h1>
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<form class="col-6 mx-auto card p-3 shadow-lg" method="POST">
    {% csrf_token %}
    <!-- Display error/success messages -->
    {% if messages %}
    <div class="alert alert-primary" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
    {% endif %}

    <!-- Render form fields -->
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% comment %} loan list view  {% endcomment %}
{% include "loan_list.html" with loans=loan_list %}



{% endblock content %}

Transactions/templates/transaction_report.html
{% extends "base.html" %}

{% block title %}
<h1 class='text-center py-4'>Transaction Report</h1>
{% endblock title %}

{% block content %}
<div class="container my-4">    
    <form method="GET" class="row g-3 mb-4">
        <div class="col-md-4">
            <label for="start_date" class="form-label">Start Date</label>
            <input type="date" class="form-control" id="start_date" name="start_date">
        </div>
        <div class="col-md-4">
            <label for="end_date" class="form-label">End Date</label>
            <input type="date" class="form-control" id="end_date" name="end_date">
        </div>
        <div class="col-md-4 align-self-end">
            <button type="submit" class="btn btn-primary w-100">Filter</button>
        </div>
    </form>
    
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Transaction Type</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Balance After Transaction</th>
                    <th scope="col">Timestamp</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ transaction.transaction_type }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.balance_after_transaction }}</td>
                    <td>{{ transaction.timestamp }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="alert alert-info mt-4">
        <strong>Balance:</strong> ${{ balance }}
    </div>
</div>
{% endblock content %}

Transactions/templates/transfer.html
{% extends "base.html" %}

{% block title %}
<h1 class='text-center py-4'>{{title}}</h1>
{% endblock title %}


{% block content %}

{% load crispy_forms_tags %}

<form class="col-6 mx-auto card p-3 shadow-lg" method="POST">
    {% csrf_token %}
    
    {% if messages %}
    <div class="alert alert-primary" role="alert">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
    {% endif %}

    <!-- Render the form fields -->
    <div class="mb-3">
        <label for="{{ form.recipient_account_number.id_for_label }}" class="form-label">
            {{ form.recipient_account_number.label }}
        </label>
        {{ form.recipient_account_number }}
    </div>
    
    <div class="mb-3">
        <label for="{{ form.amount.id_for_label }}" class="form-label">
            {{ form.amount.label }}
        </label>
        {{ form.amount }}
    </div>

    <button type="submit" class="btn btn-primary">Transfer</button>
</form>
{% endblock content %}